### ISSUE TITLE
缺少TbkOrderDetailsGetRequest

### ISSUE THREAD

**Issue by Tingday** [makelove/Taobao_topsdk#5]
AttributeError: 'module' object has no attribute 'TbkOrderDetailsGetRequest'

**Comment by superDarker** [comment]
这个接口是邀请制，有资格才会在sdk中暴露出来

**Comment by Tingday** [comment]
那可以添加吗？

**Comment by Tingday** [comment]
这都这么久了，淘宝那边竟然还没更新python3

**Comment by Tingday** [comment]
已更新，谢谢(*°∀°)=3
